//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiinasta.FiinastaAPI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/FiinastaAPI.Models")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string E_Mail {
            get {
                return this.E_MailField;
            }
            set {
                if ((object.ReferenceEquals(this.E_MailField, value) != true)) {
                    this.E_MailField = value;
                    this.RaisePropertyChanged("E_Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contacts", Namespace="http://schemas.datacontract.org/2004/07/FiinastaAPI.Models")]
    [System.SerializableAttribute()]
    public partial class Contacts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone_No_Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string E_Mail {
            get {
                return this.E_MailField;
            }
            set {
                if ((object.ReferenceEquals(this.E_MailField, value) != true)) {
                    this.E_MailField = value;
                    this.RaisePropertyChanged("E_Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone_No_ {
            get {
                return this.Phone_No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone_No_Field, value) != true)) {
                    this.Phone_No_Field = value;
                    this.RaisePropertyChanged("Phone_No_");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Spendings", Namespace="http://schemas.datacontract.org/2004/07/FiinastaAPI.Models")]
    [System.SerializableAttribute()]
    public partial class Spendings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Check_PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Entry_No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Check_Picture {
            get {
                return this.Check_PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.Check_PictureField, value) != true)) {
                    this.Check_PictureField = value;
                    this.RaisePropertyChanged("Check_Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Entry_No_ {
            get {
                return this.Entry_No_Field;
            }
            set {
                if ((this.Entry_No_Field.Equals(value) != true)) {
                    this.Entry_No_Field = value;
                    this.RaisePropertyChanged("Entry_No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FiinastaAPI.IFiinastaAPI")]
    public interface IFiinastaAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiinastaAPI/Register", ReplyAction="http://tempuri.org/IFiinastaAPI/RegisterResponse")]
        void Register(Fiinasta.FiinastaAPI.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiinastaAPI/Register", ReplyAction="http://tempuri.org/IFiinastaAPI/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(Fiinasta.FiinastaAPI.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiinastaAPI/Login", ReplyAction="http://tempuri.org/IFiinastaAPI/LoginResponse")]
        Fiinasta.FiinastaAPI.Users Login(Fiinasta.FiinastaAPI.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiinastaAPI/Login", ReplyAction="http://tempuri.org/IFiinastaAPI/LoginResponse")]
        System.Threading.Tasks.Task<Fiinasta.FiinastaAPI.Users> LoginAsync(Fiinasta.FiinastaAPI.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiinastaAPI/GetContacts", ReplyAction="http://tempuri.org/IFiinastaAPI/GetContactsResponse")]
        Fiinasta.FiinastaAPI.Contacts GetContacts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiinastaAPI/GetContacts", ReplyAction="http://tempuri.org/IFiinastaAPI/GetContactsResponse")]
        System.Threading.Tasks.Task<Fiinasta.FiinastaAPI.Contacts> GetContactsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiinastaAPI/CheckEntries", ReplyAction="http://tempuri.org/IFiinastaAPI/CheckEntriesResponse")]
        bool CheckEntries(Fiinasta.FiinastaAPI.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiinastaAPI/CheckEntries", ReplyAction="http://tempuri.org/IFiinastaAPI/CheckEntriesResponse")]
        System.Threading.Tasks.Task<bool> CheckEntriesAsync(Fiinasta.FiinastaAPI.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiinastaAPI/AddSpendings", ReplyAction="http://tempuri.org/IFiinastaAPI/AddSpendingsResponse")]
        void AddSpendings(Fiinasta.FiinastaAPI.Spendings spendings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiinastaAPI/AddSpendings", ReplyAction="http://tempuri.org/IFiinastaAPI/AddSpendingsResponse")]
        System.Threading.Tasks.Task AddSpendingsAsync(Fiinasta.FiinastaAPI.Spendings spendings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiinastaAPI/GetSpendings", ReplyAction="http://tempuri.org/IFiinastaAPI/GetSpendingsResponse")]
        Fiinasta.FiinastaAPI.Spendings[] GetSpendings(string period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiinastaAPI/GetSpendings", ReplyAction="http://tempuri.org/IFiinastaAPI/GetSpendingsResponse")]
        System.Threading.Tasks.Task<Fiinasta.FiinastaAPI.Spendings[]> GetSpendingsAsync(string period);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFiinastaAPIChannel : Fiinasta.FiinastaAPI.IFiinastaAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiinastaAPIClient : System.ServiceModel.ClientBase<Fiinasta.FiinastaAPI.IFiinastaAPI>, Fiinasta.FiinastaAPI.IFiinastaAPI {
        
        public FiinastaAPIClient() {
        }
        
        public FiinastaAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiinastaAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiinastaAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiinastaAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Register(Fiinasta.FiinastaAPI.Users user) {
            base.Channel.Register(user);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(Fiinasta.FiinastaAPI.Users user) {
            return base.Channel.RegisterAsync(user);
        }
        
        public Fiinasta.FiinastaAPI.Users Login(Fiinasta.FiinastaAPI.Users user) {
            return base.Channel.Login(user);
        }
        
        public System.Threading.Tasks.Task<Fiinasta.FiinastaAPI.Users> LoginAsync(Fiinasta.FiinastaAPI.Users user) {
            return base.Channel.LoginAsync(user);
        }
        
        public Fiinasta.FiinastaAPI.Contacts GetContacts() {
            return base.Channel.GetContacts();
        }
        
        public System.Threading.Tasks.Task<Fiinasta.FiinastaAPI.Contacts> GetContactsAsync() {
            return base.Channel.GetContactsAsync();
        }
        
        public bool CheckEntries(Fiinasta.FiinastaAPI.Users user) {
            return base.Channel.CheckEntries(user);
        }
        
        public System.Threading.Tasks.Task<bool> CheckEntriesAsync(Fiinasta.FiinastaAPI.Users user) {
            return base.Channel.CheckEntriesAsync(user);
        }
        
        public void AddSpendings(Fiinasta.FiinastaAPI.Spendings spendings) {
            base.Channel.AddSpendings(spendings);
        }
        
        public System.Threading.Tasks.Task AddSpendingsAsync(Fiinasta.FiinastaAPI.Spendings spendings) {
            return base.Channel.AddSpendingsAsync(spendings);
        }
        
        public Fiinasta.FiinastaAPI.Spendings[] GetSpendings(string period) {
            return base.Channel.GetSpendings(period);
        }
        
        public System.Threading.Tasks.Task<Fiinasta.FiinastaAPI.Spendings[]> GetSpendingsAsync(string period) {
            return base.Channel.GetSpendingsAsync(period);
        }
    }
}
