//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiinastaAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class Contacts
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string E_Mail { get; set; }
        [DataMember]
        public string Address { get; set; }
        [DataMember]
        public string Phone_No_ { get; set; }
    }
}
