//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiinastaAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class Spendings
    {
        [DataMember]
        public int UserID { get; set; }
        [DataMember]
        public int Entry_No_ { get; set; }
        [DataMember]
        public double Amount { get; set; }
        [DataMember]
        public string Category { get; set; }
        [DataMember]
        public System.DateTime Date { get; set; }
        [DataMember]
        public string Comment { get; set; }
        [DataMember]
        public string Check_Picture { get; set; }
    }
}
